name: Automated Code Review with AWS Bedrock

on:
  workflow_dispatch:

jobs:
  code_review:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install boto3

      # Step 4: Process CodeGuru results and correct code using Llama 3
      - name: Process CodeGuru Results with Llama 3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          if [ -f "codeguru_results.json" ]; then
            echo "Found codeguru_results.json, proceeding with Llama 3 correction."
            python src/bedrock_code_review.py codeguru_results.json  # Ensure correct path to the script
          else
            echo "ERROR: codeguru_results.json not found in the root folder."
            exit 1
          fi

      # Step 5: Commit and push corrections back to the repo
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated code corrections based on CodeGuru results via Llama 3" || echo "No changes to commit"
          git push origin master  # Ensure you're pushing to the correct branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

